#!/usr/bin/env bash
# Sync desktop-agent version from frontend APP_VERSION (app-meta.ts).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
APP_META="$ROOT/frontend/src/lib/app-meta.ts"
VER="$(grep -E "^export const APP_VERSION = " "$APP_META" | head -1 | sed -E "s/.*'([^']+)'.*/\1/")"

if [[ -z "$VER" ]]; then
  echo "sync-agent-version: could not read APP_VERSION from $APP_META" >&2
  exit 1
fi

PLIST="$ROOT/desktop-agent/mac/Contents/Info.plist"
if [[ -f "$PLIST" ]]; then
  python3 - "$PLIST" "$VER" <<'PY'
import plistlib
import sys
from pathlib import Path

path = Path(sys.argv[1])
ver = sys.argv[2]
with path.open("rb") as f:
    data = plistlib.load(f)
data["CFBundleShortVersionString"] = ver
data["CFBundleVersion"] = ver
with path.open("wb") as f:
    plistlib.dump(data, f, fmt=plistlib.FMT_XML)
PY
fi

ISS_VER="$ROOT/desktop-agent/windows/version.iss"
cat > "$ISS_VER" <<EOF
; Auto-generated by scripts/sync-agent-version.sh — do not edit manually
#define MyAppVersion "$VER"
EOF

echo "Synced desktop-agent version to $VER (Info.plist + windows/version.iss)"
